# source: https://github.com/TRIGONIM/lua-long-polling/blob/main/.github/workflows/luarocks-release.yml
name: "Luarocks Release"

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

jobs:
  luarocks-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          extra_luarocks_args: --force # update lr version on commit
          summary: "Collection of middlewares for lua-express"
          detailed_description: |
            lua-express (https://github.com/TRIGONIM/lua-express) is a lua port of express.js.
            There is the lua versions of the original middlewares like cookie-parser,
            body-parser, and custom ones like rate-limiter, validator, etc.
            GitHub: https://github.com/TRIGONIM/lua-express-middlewares
          labels: |
            lua-express
